### PR TITLE
fix(jsdoc): escape unknown tags rather than omit them

### LINKED ISSUE #325: Upgrading tsickle for angular causes JSDoc to be too escapy
upgrading from tsickle@0.2.2 to 0.2.3 causes undesirable escaping in Angular's JSDoc

eg.
```
/**
 * Construct {\@link CompileDirectiveMetadata} from {\@link ComponentTypeMetadata} and a selector.
 * @param {?} typeReference
 * @param {?} compMeta
 * @return {?}
 */
```

we shouldn't need to escape `@link`

Also the `@stable` annotation is completely dropped.

blocks https://github.com/angular/angular/pull/13471
/cc @IgorMinar

### PR DESCRIPTION
**Pull request by alexeagle**
Fixes #325

### CODE REVIEW

File: src/jsdoc.ts [hunk 1]
```diff
@@ -177,14 +166,29 @@ export function parse(comment: string): {tags: Tag[], warnings?: string[]}|null
...
+        // 1) If we pass through these non-Closure tags, the user will
+        //    get a warning from Closure, and the point of tsickle is
+        //    to insulate the user from Closure.
+        // 2) The output of tsickle is for Closure but also may be read
+        //    by humans, for example non-TypeScript users of Angular.
+        // 3) Finally, we don't want to warn because users should be
+        //    free to add whichever JSDoc they feel like.  If the user
+        //    wants help ensuring they didn't typo a tag, that is the
+        //    responsibility of a linter.
+        tag.escape = true;
```
Comment (evmar) [inline src/jsdoc.ts]: Rather than adding an attribute here, you can just look it up down when we call tagToString.

Comment (alexeagle) [inline src/jsdoc.ts]: yes, nice simplification, ptal
