### PR TITLE
fix isBlackListed check on Windows

### LINKED ISSUE #443: test 'tsickle compiler host passes blacklisted paths' fails on Windows
Last remaining test that fails on Windows:

```
1) tsickle compiler host passes blacklisted paths:
   AssertionError: expected 'let /** @type {!Banned} */ b: Banned = {b: "a"};' to include '/** @type {?} */ b: Banned'
   at Context.<anonymous> (D:\workspace\b-strauss\test\e2e_tsickle_compiler_host_test.ts:83:23)
```

### PR DESCRIPTION
**Pull request by b-strauss**
Rearranged the code a bit, so the normalization is not done if the method returns early.

Fixes #443

### CODE REVIEW

File: src/type-translator.ts [hunk 1]
```diff
@@ -6,6 +6,7 @@
  * found in the LICENSE file at https://angular.io/license
  */
 
+import * as nodePath from 'path';
```
Comment (mprobst) [inline src/type-translator.ts]: nit: use `pathlib` as the alias (we have other places doing that, too), or, preferably rename the local variables to avoid the collision?

File: src/type-translator.ts [hunk 2]
```diff
@@ -503,13 +504,15 @@ export class TypeTranslator {
   /** @return true if sym should always have type {?}. */
   isBlackListed(symbol: ts.Symbol): boolean {
     if (this.pathBlackList === undefined) return false;
-    const pathBlackList = this.pathBlackList;
     if (symbol.declarations === undefined) {
       this.warn('symbol has no declarations');
       return true;
     }
+    // Normalize paths to not break checks on Windows.
+    const pathBlackList = new Set<string>(
```
Comment (mprobst) [inline src/type-translator.ts]: can we arrange the code such that we only do this once, e.g. in the constructor, instead of on every check? This method is called frequently, doing the work over and over again will likely be a performance issue.

Comment (b-strauss) [inline src/type-translator.ts]: Should I keep the auto assignment of `pathBlackList` and just overwrite the property like this in the constructor?

```typescript
this.pathBlackList = new Set<string>(
        Array.from(this.pathBlackList.values()).map(path => nodePath.normalize(path)));
```

File: src/type-translator.ts (hunk 1 above)
Comment (b-strauss) [inline src/type-translator.ts]: I'll rename the variable to `fileName`.

File: src/type-translator.ts (hunk 2 above)
Comment (mprobst) [inline src/type-translator.ts]: Yes, that sounds about right. Bonus points for making the property `readonly` :-)

Comment (b-strauss) [inline src/type-translator.ts]: Maybe we could change everything in the constructor to readonly? Seems like nothing gets overwritten later.

**Comment by mprobst** [comment]
SGTM.

Benjamin Strauß <notifications@github.com> schrieb am Di., 21. März 2017 um
11:14 Uhr:

**Comment by b-strauss** [comment]
I'll apply the changes later when I get home from work.

**Comment by mprobst** [comment]
Thanks!

Benjamin Strauß <notifications@github.com> schrieb am Di., 21. März 2017 um
11:19 Uhr:

File: src/type-translator.ts [hunk 3]
```diff
@@ -503,14 +511,13 @@ export class TypeTranslator {
   /** @return true if sym should always have type {?}. */
   isBlackListed(symbol: ts.Symbol): boolean {
     if (this.pathBlackList === undefined) return false;
-    const pathBlackList = this.pathBlackList;
```
Comment (evmar) [inline src/type-translator.ts]: The reason for this line was to save the non-null pathBlackList.
