### PR TITLE
fix(ctorParams): allow undefined ctorParam type

### LINKED ISSUE #139: Emit `ctorParameters` also if there is not type but decorators
E.g.
```
class ViewUtils {
  constructor(@Inject(APP_ID) private _appId: string) {}
}
```

Right now, this emits `ViewUtils.ctorParameters = [null];`, but it should emit
```
    ViewUtils.ctorParameters = [
        { type: undefined, decorators: [{ type: decorators_1.Inject, args: [application_tokens_1.APP_ID,] },] },
    ];
```

### PR DESCRIPTION
**Pull request by alexeagle**
Fixes #139

### CODE REVIEW

File: src/decorator-annotator.ts [hunk 1]
```diff
@@ -65,16 +66,17 @@ class ClassRewriter extends Rewriter {
...
         ctorParameters.push([paramCtor, decorators]);
       } else {
         ctorParameters.push(null);
       }
     }
 
+
     // Use the ctor parameter metadata only if the class or the ctor was decorated.
     if (this.decorators || hasDecoratedParam) {
+      console.log(ctorParameters);
```
Comment (tbosch) [inline src/decorator-annotator.ts]: Remove this

File: src/decorator-annotator.ts [hunk 2]
```diff
@@ -143,6 +145,7 @@ class ClassRewriter extends Rewriter {
           `static ctorParameters: {type: Function, decorators?: DecoratorInvocation[]}[] = [\n`);
       for (let param of this.ctorParameters) {
         if (!param) {
+          console.log("found a null elemen t!");
```
Comment (tbosch) [inline src/decorator-annotator.ts]: Remove this
